title: "Edulabs"
description: "Documentation et plus"
baseurl: ""
url: "https://dev.edulabs.fr/"

permalink: pretty
theme: null

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

search_enabled: true
enable_copy_code_button: true
heading_anchors: true

aux_links:
  "Edulabs sur GitHub":
    - ""

gh_edit_link: false
gh_edit_link_text: "Modifier cette page sur GitHub"
gh_edit_repository: "https://github.com/edulabs-fr/edulabs-fr.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

color_scheme: light

footer_content: '© 2025 Edulabs. Distribué sous <a href="https://github.com/edulabs-fr/edulabs-fr.github.io/blob/main/LICENSE">MIT License</a>.'
