title: "Edulabs"
description: "Documentation et plus"
baseurl: ""
url: "https://edulabs-fr.github.io"
repository: "edulabs-fr/edulabs"

permalink: pretty

remote_theme: just-the-docs/just-the-docs

search_enabled: true
enable_copy_code_button: true
heading_anchors: true

aux_links:
  "Edulabs sur GitHub":
    - "https://github.com/edulabs-fr/edulabs"

aux_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: "Modifier cette page sur GitHub"
gh_edit_repository: "https://github.com/edulabs-fr/edulabs"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

color_scheme: light

footer_content: '© 2025 Edulabs. Distribué sous <a href="https://github.com/edulabs-fr/edulabs/blob/main/LICENSE">MIT License</a>.'
